// Runtime configuration for local and cloud deployments.
import { z } from "zod";
const schema = z.object({
  PORT: z.coerce.number().default(8080),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  SOLANA_RPC_URL: z.string().default("https://api.devnet.solana.com"),
  SOLANA_CLUSTER_ID: z.enum(["solana-devnet", "solana-testnet", "solana-mainnet-beta"]).default("solana-devnet"),
  SOLANA_EXPECTED_GENESIS_HASH: z.string().default(""),
  ENABLE_LIVE_SUBMISSION: z.string().default("false"),
  JUPITER_QUOTE_URL: z.string().default("https://api.jup.ag/swap/v1/quote"),
  JUPITER_API_KEY: z.string().optional(),
  DRY_RUN: z.string().default("true"),
  MAX_ORDER_USD: z.coerce.number().default(10000),
  MAX_SLIPPAGE_BPS: z.coerce.number().default(100),
  MAX_ROUTE_DRIFT_RATIO: z.coerce.number().default(0.15),
  MAX_PRIORITY_FEE_LAMPORTS: z.coerce.number().default(10000),
  RPC_TIMEOUT_MS: z.coerce.number().default(5000),
  ENABLE_ROUTE_CONSISTENCY_GUARD: z.string().default("true"),
  QUOTE_PROVIDER_RETRY_COUNT: z.coerce.number().default(2),
  QUOTE_PROVIDER_RETRY_DELAY_MS: z.coerce.number().default(150),
  QUOTE_PROVIDER_CIRCUIT_BREAKER_THRESHOLD: z.coerce.number().default(3),
  QUOTE_PROVIDER_CIRCUIT_BREAKER_RESET_MS: z.coerce.number().default(60000),
  TX_NONCE_MAX_AGE_MS: z.coerce.number().default(300000),
  API_AUTH_TOKENS: z.string().default("[]"),
  NITRO_TRUSTED_ROOT_SHA256: z.string().default(""),
  NITRO_PCR3_P1: z.string().default(""),
  NITRO_PCR3_P2: z.string().default(""),
  NITRO_PCR3_P3: z.string().default(""),
  NITRO_PCR3_COORDINATOR: z.string().default(""),
  NITRO_PCR4_P1: z.string().default(""),
  NITRO_PCR4_P2: z.string().default(""),
  NITRO_PCR4_P3: z.string().default(""),
  NITRO_PCR4_COORDINATOR: z.string().default(""),
  NITRO_PCR8: z.string().default(""),
  ATTESTATION_CHALLENGE_TTL_SECONDS: z.coerce.number().int().min(15).max(300).default(60),
  ATTESTATION_MAX_AGE_MS: z.coerce.number().int().min(1000).max(300000).default(60000),
  NITRO_SIGNING_KEY_ID: z.string().default(""),
  NITRO_EXPECTED_PUBLIC_KEY_HEX: z.string().default(""),
  POLICY_AUTHORITY_PUBLIC_KEY_HEX: z.string().default(""),
});
export const env = schema.parse(process.env);
